In [1]:
import pandas as pd 
import json 
import numpy as np
from pathlib import Path
import ast

In [37]:
DATA_DIR = "../data/clean_tables/"

In [22]:
pd.read_csv(DATA_DIR + "artists", index_col=0)

       index  artist_id      artist_name
0          0      99650              753
1          1     108809       dasstudach
2          2     104584         Kamafaka
3          3     137083         LEX LEDU
4          4     106726          Neagles
...      ...        ...              ...
71344    455     176573        darialism
71345    456     124019           äsc3ea
71346    459      98184            AC130
71347    469      89917  Andrew Valevsky
71348    471     105004        Chocollab

[71349 rows x 3 columns]

In [23]:
pd.read_csv(DATA_DIR + "promoters", index_col=0)

       index  promoter_id        promoter_name
0          0     174492.0         RAVEolution
1          1     180621.0           Fabrika ET
2          0          NaN                  NaN
3          0     123486.0     Puur Techno Rave
4          1      38800.0                DGTL
...      ...          ...                  ...
30994    321     178383.0  HOT GIRLS GET DIRTY
30995    322     175960.0     Michael Yermakov
30996    324     178534.0            Zdybanka
30997    336     179405.0               Brukxt
30998    352     105032.0                VTIXA

[30999 rows x 3 columns]

In [24]:
pd.read_csv(DATA_DIR + "venues", index_col=0)

,index,venue_id,venue_name,venue_address,venue_area_id,venue_lat,venue_lng
0,0,277302,TBA - lakeside campground in debrezeyit,NaN,458,0.000000,0.000000
1,1,284754,Zoma Museum Entoto Park,"Addis Ababa Ethiopia, Zoma Muesum-Entoto Park",458,8.980000,38.730000
2,0,284567,TBA - delete,NaN,417,0.000000,0.000000
3,0,188055,Ijland,"Tt. Vasumweg 171, 1033 SG Amsterdam",29,52.411540,4.877560
4,1,4859,NDSM Docklands,"Kinetisch Noord, Tt. Neveritaweg 15; 1033 Amst...",29,52.401147,4.896282
...,...,...,...,...,...,...,...
33394,348,149453,Bursa Gallery,"Konstantinivska 11B, Kyiv, Ukraine",517,50.450100,30.523400
33395,352,284608,TBA - Ivano-Frankivsk - secret place,NaN,165,0.000000,0.000000
33396,366,172703,Zbirka,"Konstantynivska, 21, Kyiv, Ukraine",517,50.450100,30.523400
33397,372,286690,TBA - INKI BAR,NaN,517,0.000000,0.000000
33398,373,236710,TBA - Heaven Space,NaN,517,0.000000,0.000000

In [ ]:
place = pd.read_csv(DATA_DIR + "place", index_col=0)


def get_country_area_subarea(x):
    x = x.split('_')

    try:
        country = x[0]
    except:
        country = np.nan
    try: 
        area = x[1]
    except:
        area = np.nan 
    try:
        subarea = x[2]
    except:
        subarea = np.nan
    return [country, area, subarea]
    
area = [get_country_area_subarea(x) for x in place.place_name.values]


place_df = pd.DataFrame({'place_id':place.place_id,
                          'country' : [x[0] for x in area],
                          'area' :  [x[1] for x in area],
                          'subarea' : [x[2] for x in area]})

In [47]:
place

     place_id             place_name
0         163           Colombia_All
1         466        Afghanistan_All
2          99            Denmark_All
3         223            Albania_All
4         669         Albania_Tirana
..        ...                    ...
650       511            Vanuatu_All
651       554  Vietnam_HoChiMinhCity
652       556          Vietnam_Hanoi
653       465             Zambia_All
654       313           Zimbabwe_All

[655 rows x 2 columns]

In [ ]:



# place_df = pd.DataFrame({
# 'country' : [x[0] for x in area],
#              'area' :  [x[1] for x in area],
#              'subarea' : [x[2] for x in area]})

In [53]:
place_df[place_df.country == "UnitedKingdom"]

     place_id        country             area     subarea
14         16  UnitedKingdom            North         NaN
31          3  UnitedKingdom              NaN         NaN
127        30  UnitedKingdom         Scotland         NaN
206        15  UnitedKingdom       South+East         NaN
273        13  UnitedKingdom           London         NaN
312        14  UnitedKingdom         Midlands         NaN
544        24  UnitedKingdom       West+Wales         NaN
567        35  UnitedKingdom  NorthernIreland         NaN
577       342  UnitedKingdom         Scotland    Aberdeen
578       534  UnitedKingdom  NorthernIreland     Belfast
579       516  UnitedKingdom         Midlands  Birmingham
580       535  UnitedKingdom       South+East    Brighton
581       446  UnitedKingdom       West+Wales     Bristol
582       518  UnitedKingdom       West+Wales     Cardiff
583       539  UnitedKingdom         Scotland      Dundee
584       341  UnitedKingdom         Scotland   Edinburgh
585       340  UnitedKingdom         Scotland     Glasgow
586       346  UnitedKingdom            North       Leeds
587       343  UnitedKingdom            North   Liverpool
588       344  UnitedKingdom            North  Manchester
589       544  UnitedKingdom       Nottingham         NaN
590       345  UnitedKingdom            North   Newcastle
591       520  UnitedKingdom        Sheffield         NaN
592       686  UnitedKingdom       South+East  Portsmouth
593       685  UnitedKingdom      Southampton         NaN

In [27]:
pd.read_csv(DATA_DIR + "events", index_col=0)

,index,id,title,description,start_time,lineup,linup_aids,genres,interested_count,is_festival,has_secret_venue,is_ticketed,flyer_photo,venue_id,promoter_id
0,0,2284798,RAVEolution,RAVEolution will be hosting a private lakeside...,2025-10-18T15:00:00.000,"[{'id': None, 'name': 'Yuhans'}, {'id': None, ...",NaN,"['Techno', 'Afro Tech']",0,False,False,False,https://images.ra.co/6db2f9cfaeab206009f15a77f...,277302,174492.0
1,1,2363220,ZOYA- Fua Fua Té,"Zoya is back!! And this time, we’re doing it d...",2026-02-08T10:00:00.000,"[{'id': None, 'name': 'SamYF'}, {'id': None, '...",NaN,"['Electro', 'Afro Tech']",0,False,False,False,https://images.ra.co/385c84a825c0b369c3ddd6710...,284754,180621.0
2,0,2360393,Jungle monkey x Traumer,NaN,2026-02-07T21:30:00.000,"[{'id': None, 'name': 'TBF'}]",NaN,"['Techno', 'Tech House']",0,False,False,False,NaN,284567,NaN
3,0,1828192,Puur Techno Rave INDOOR FESTIVAL 2024,PUUR TECHNO RAVE x CØLLECTVE\n\nGet ready for ...,2025-03-02T13:00:00.000,"[{'id': '99650', 'name': '753'}, {'id': None, ...","99650,108809,104584,137083,106726,143329,6398,...","['Techno', 'Industrial']",61,False,False,False,https://images.ra.co/4979845aadee0a5271d447b87...,188055,123486.0
4,1,1900358,DGTL Amsterdam 2025 (SOLD OUT),Important information for ticket buyers: You w...,2025-04-18T21:00:00.000,"[{'id': None, 'name': 'SATURDAY APRIL 19'}, {'...","113818,96823,102591,141268,118368,81806,97172,...","['Techno', 'House']",988,True,False,True,https://images.ra.co/190c944e560ed410fe2ffec30...,4859,38800.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
247197,367,2380035,Практика Усвідомленого Прослуховування,NaN,2026-03-01T17:00:00.000,"[{'id': '89917', 'name': 'Andrew Valevsky'}, {...","89917,119595","['Ambient', 'Downtempo']",1,False,False,False,https://images.ra.co/5fcf1c6ecc0b3a4f8963a9dd5...,281910,NaN
247198,368,2380512,SUPERPOSITION III,Three trajectories of contemporary techno conv...,2026-02-28T15:00:00.000,"[{'id': '112756', 'name': 'JANE (UA)'}, {'id':...","112756,44133,1835",[],1,False,False,False,https://images.ra.co/b1b236365c6db9880c82e0fe3...,177458,NaN
247199,369,2380899,The Brukxt Project 3 Years Anniversary,"Хто памʼятає, як усе починалось?\nПроєктор у к...",2026-02-27T18:00:00.000,"[{'id': '128733', 'name': 'Hanna (UA)'}, {'id'...","128733,112375,118435,108464,136423,101437,1050...",[],0,False,False,False,https://images.ra.co/b548b17199fcb3f62e675ec61...,225873,112462.0
247200,372,2384936,Karry G Performing Live at INKI BAR,Get ready for an unforgettable evening as DJ K...,2025-03-14T18:00:00.000,"[{'id': '140661', 'name': 'Karry G'}]",140661,"['Progressive House', 'Techno']",0,False,False,False,https://images.ra.co/7e6c280aa0feb08745683d184...,286690,NaN
247201,373,2384943,Karry G at Heaven Space,Step into the immersive world of melodic beats...,2025-10-14T22:00:00.000,"[{'id': '140661', 'name': 'Karry G'}]",140661,"['Progressive House', 'Techno']",0,False,False,False,https://images.ra.co/a7f7a29dba620f0f33382405a...,236710,NaN