In [1]:
import pandas as pd 
import json 
import numpy as np
from pathlib import Path
import ast

In [37]:
DATA_DIR = "../data/clean_tables/"

In [ ]:
pd.read_csv(DATA_DIR + "artists", index_col=0)

       index  artist_id      artist_name
0          0      99650              753
1          1     108809       dasstudach
2          2     104584         Kamafaka
3          3     137083         LEX LEDU
4          4     106726          Neagles
...      ...        ...              ...
71344    455     176573        darialism
71345    456     124019           äsc3ea
71346    459      98184            AC130
71347    469      89917  Andrew Valevsky
71348    471     105004        Chocollab

[71349 rows x 3 columns]

In [23]:
pd.read_csv(DATA_DIR + "promoters", index_col=0)

       index  promoter_id        promoter_name
0          0     174492.0         RAVEolution
1          1     180621.0           Fabrika ET
2          0          NaN                  NaN
3          0     123486.0     Puur Techno Rave
4          1      38800.0                DGTL
...      ...          ...                  ...
30994    321     178383.0  HOT GIRLS GET DIRTY
30995    322     175960.0     Michael Yermakov
30996    324     178534.0            Zdybanka
30997    336     179405.0               Brukxt
30998    352     105032.0                VTIXA

[30999 rows x 3 columns]

In [24]:
pd.read_csv(DATA_DIR + "venues", index_col=0)

,index,venue_id,venue_name,venue_address,venue_area_id,venue_lat,venue_lng
0,0,277302,TBA - lakeside campground in debrezeyit,NaN,458,0.000000,0.000000
1,1,284754,Zoma Museum Entoto Park,"Addis Ababa Ethiopia, Zoma Muesum-Entoto Park",458,8.980000,38.730000
2,0,284567,TBA - delete,NaN,417,0.000000,0.000000
3,0,188055,Ijland,"Tt. Vasumweg 171, 1033 SG Amsterdam",29,52.411540,4.877560
4,1,4859,NDSM Docklands,"Kinetisch Noord, Tt. Neveritaweg 15; 1033 Amst...",29,52.401147,4.896282
...,...,...,...,...,...,...,...
33394,348,149453,Bursa Gallery,"Konstantinivska 11B, Kyiv, Ukraine",517,50.450100,30.523400
33395,352,284608,TBA - Ivano-Frankivsk - secret place,NaN,165,0.000000,0.000000
33396,366,172703,Zbirka,"Konstantynivska, 21, Kyiv, Ukraine",517,50.450100,30.523400
33397,372,286690,TBA - INKI BAR,NaN,517,0.000000,0.000000
33398,373,236710,TBA - Heaven Space,NaN,517,0.000000,0.000000

In [ ]:
place_df = pd.read_csv(DATA_DIR + "place", index_col=0)

In [57]:
place_df.head()

   place_id      country    area subarea
0       163     Colombia     All     NaN
1       466  Afghanistan     All     NaN
2        99      Denmark     All     NaN
3       223      Albania     All     NaN
4       669      Albania  Tirana     NaN

In [58]:
place_df[place_df.country == 'Denmark']

     place_id  country        area subarea
2          99  Denmark         All     NaN
173       403  Denmark         All  Aarhus
174       402  Denmark  Copenhagen     NaN
175       515  Denmark      Odense     NaN

In [56]:
place_df[place_df.country == "UnitedKingdom"]

     place_id        country             area     subarea
14         16  UnitedKingdom            North         NaN
31          3  UnitedKingdom              NaN         NaN
127        30  UnitedKingdom         Scotland         NaN
206        15  UnitedKingdom       South+East         NaN
273        13  UnitedKingdom           London         NaN
312        14  UnitedKingdom         Midlands         NaN
544        24  UnitedKingdom       West+Wales         NaN
567        35  UnitedKingdom  NorthernIreland         NaN
577       342  UnitedKingdom         Scotland    Aberdeen
578       534  UnitedKingdom  NorthernIreland     Belfast
579       516  UnitedKingdom         Midlands  Birmingham
580       535  UnitedKingdom       South+East    Brighton
581       446  UnitedKingdom       West+Wales     Bristol
582       518  UnitedKingdom       West+Wales     Cardiff
583       539  UnitedKingdom         Scotland      Dundee
584       341  UnitedKingdom         Scotland   Edinburgh
585       340  UnitedKingdom         Scotland     Glasgow
586       346  UnitedKingdom            North       Leeds
587       343  UnitedKingdom            North   Liverpool
588       344  UnitedKingdom            North  Manchester
589       544  UnitedKingdom       Nottingham         NaN
590       345  UnitedKingdom            North   Newcastle
591       520  UnitedKingdom        Sheffield         NaN
592       686  UnitedKingdom       South+East  Portsmouth
593       685  UnitedKingdom      Southampton         NaN